function data = importSensortherm(filename, dataLines)
%IMPORTFILE Import data from a text file
%  H3221191020210731000193 = IMPORTFILE(FILENAME) reads data from text
%  file FILENAME for the default selection.  Returns the data as a table.
%
%  H3221191020210731000193 = IMPORTFILE(FILE, DATALINES) reads data for
%  the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  H3221191020210731000193 = importfile("E:\data-sensortherm\20210731\H322-11910_20210731_000193.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 18-Sep-2021 16:50:08

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 7);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ";";

% Specify column names and types
opts.VariableNames = ["Time", "Recordtime", "Temp", "UnitTemp", "Ctemp", "UnitCtemp", "EmissivityRatio"];
opts.SelectedVariableNames = opts.VariableNames;
opts.VariableTypes = ["datetime", "datetime", "double", "string", "double", "string", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

opts = setvaropts(opts, "Time", "InputFormat", "HH:mm:ss,SSSSSS");
opts = setvaropts(opts, "Recordtime", "InputFormat", "HH:mm:ss,SSSSSS");

% Specify variable properties
opts = setvaropts(opts, [ "UnitTemp", "UnitCtemp"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, [ "UnitTemp", "UnitCtemp",], "EmptyFieldRule", "auto");
opts = setvaropts(opts, ["Temp", "Ctemp"] , "DecimalSeparator", ",");

% Import the data
data = readtable(filename, opts);

end