function lay_data = readCSV(filename, dataLines)
%IMPORTFILE Import data from a text file
%  LAY022020032122401337 = IMPORTFILE(FILENAME) reads data from text
%  file FILENAME for the default selection.  Returns the data as a table.
%
%  LAY022020032122401337 = IMPORTFILE(FILE, DATALINES) reads data for
%  the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  lay022020032122401337 = importfile("C:\temp\cube1\lay02_2020-03-21-22-40-13-37.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 22-Mar-2020 10:14:14

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 14);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Id", "DataDate", "DataTime", "PrintDate", "PrintTime", "PosX", "PosY", "PosZ", "PosB", "PosC", "VelCmd", "LaserPcmd", "LaserPfdbck", "FlowWatch"];
opts.VariableTypes = ["double", "string", "double", "datetime", "datetime", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "DataDate", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "DataDate", "EmptyFieldRule", "auto");
opts = setvaropts(opts, "PrintDate", "InputFormat", "yyyy-MM-dd");
opts = setvaropts(opts, "PrintTime", "InputFormat", "HH:mm:ss.SSSSSS");

% Import the data
lay_data = readtable(filename, opts);

end